"""cambiar tipos num_pedido y valor_volumetrico

Revision ID: 76ffd8558b11
Revises: 8f1a5aea0c7b
Create Date: 2026-09-11 21:06:08.447354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ffd8558b11'
down_revision: Union[str, Sequence[str], None] = '8f1a5aea0c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedido', 'num_pedido',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('pedido', 'valor_volumetrico',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedido', 'valor_volumetrico',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('pedido', 'num_pedido',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
